___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
b= np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [12]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [20]:
np.random.rand(1)

array([0.83281558])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
np.random.randn(25)

array([ 1.10453752,  0.44080907, -1.50446708, -0.49695713,  0.20137476,
        0.27337689,  0.41820603, -1.27503536, -0.04164662,  0.97551865,
       -0.97135657,  0.5395782 , -0.48189645,  0.16255659,  1.59771589,
       -1.84787028, -0.02537666, -0.70833882,  0.98179242, -0.37313736,
       -0.85814052, -0.12522382, -0.27640223,  0.64377982,  0.19557714])

#### Create the following matrix:

In [22]:
np.random.randn(10,10)

array([[-0.50554855,  0.14026548,  1.94831756, -0.34782876,  0.12668755,
         0.4789889 , -0.02325517, -0.58327023, -1.51491268, -0.2846997 ],
       [-0.10456815,  0.24339503,  1.07196201,  0.40180934,  1.74650258,
         0.05396481, -1.16793338,  0.72873217, -1.61014871,  0.13965589],
       [-0.09691453, -1.05657075,  0.3091242 , -0.31095324, -1.91619185,
        -0.05183803,  0.64634609,  0.15423105, -0.59452032,  0.46373201],
       [ 0.67547209,  1.50522549,  0.77560408,  0.9225604 , -1.10599315,
         0.05691625, -1.28815456,  0.69545045,  1.38877996,  1.37034461],
       [-2.33677042, -1.28941212, -0.5058573 , -0.86702716,  0.22353635,
        -0.07166598,  0.39795529,  1.05379796,  1.29714458,  1.0037623 ],
       [ 1.11151795,  0.24131591,  0.40061345,  1.5000451 ,  1.38144909,
         0.32017405, -0.01257066, -0.93506748, -0.47275853,  0.96905586],
       [-0.61723212, -0.58306539, -1.14361092,  2.16420254, -2.38897986,
         0.51350271, -0.14269586,  0.31738703

#### Create an array of 20 linearly spaced points between 0 and 1:

In [23]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [33]:
mat[2:5,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [48]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [50]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [51]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [52]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [53]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!